# Generated by Django 5.1.15 on 2026-02-21 14:22

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
