# Generated by Django 5.1.15 on 2026-02-21 17:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CONSENT_GRANT', 'Consent Grant'), ('CONSENT_REVOKE', 'Consent Revoke')], db_index=True, max_length=20)),
                ('resource_type', models.CharField(db_index=True, max_length=100)),
                ('resource_id', models.CharField(db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('electronic_signature', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'managed': True,
            },
        ),
    ]
