# Generated by Django 5.1.15 on 2026-02-21 14:22

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='electronic_signature',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, default=''),
        ),
    ]
