# Generated by Django 5.1.15 on 2026-02-21 18:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('triage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('method', models.CharField(choices=[('SHAP', 'SHAP (Shapley Additive Explanations)'), ('LIME', 'LIME (Local Interpretable Model-agnostic Explanations)'), ('ATTENTION', 'Attention-Based'), ('RULE_BASED', 'Rule-Based Analysis')], db_index=True, default='SHAP', max_length=20)),
                ('summary', models.TextField(help_text='Human-readable explanation of the AI decision.')),
                ('global_feature_importance', models.JSONField(default=list, help_text='Ranked list of features by overall importance.')),
                ('model_version', models.CharField(blank=True, default='', max_length=100)),
                ('computation_time_ms', models.IntegerField(blank=True, help_text='Time taken to generate this explanation in milliseconds.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional XAI metadata (thresholds, baselines, etc.).')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('triage_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xai_explanation', to='triage.triageresult')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'xai_explanations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_name', models.CharField(help_text='Machine-readable feature identifier.', max_length=255)),
                ('feature_category', models.CharField(choices=[('SYMPTOM', 'Symptom'), ('VITAL_SIGN', 'Vital Sign'), ('BIOMARKER', 'Biomarker'), ('HISTORY', 'Medical History'), ('IMAGE', 'Image Feature'), ('DEMOGRAPHIC', 'Demographic')], db_index=True, max_length=20)),
                ('contribution_score', models.FloatField(help_text='SHAP value: positive pushes toward diagnosis, negative away. Range -1.0 to 1.0.')),
                ('direction', models.CharField(choices=[('POSITIVE', 'Increases risk / supports diagnosis'), ('NEGATIVE', 'Decreases risk / contradicts diagnosis'), ('NEUTRAL', 'Minimal impact')], max_length=10)),
                ('display_name', models.CharField(blank=True, default='', help_text="Human-readable feature name (e.g. 'Headache Severity').", max_length=255)),
                ('display_value', models.CharField(blank=True, default='', help_text="Human-readable value (e.g. 'Severe', '140/90 mmHg').", max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text="Natural language explanation of this feature's impact.")),
                ('rank', models.IntegerField(default=0, help_text='Importance rank (1 = most important).')),
                ('explanation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_contributions', to='xai.explanation')),
            ],
            options={
                'db_table': 'xai_feature_contributions',
                'ordering': ['rank'],
            },
        ),
    ]
