# Generated by Django 5.1.15 on 2026-02-22 00:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
        ('xai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstAidPrescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('symptoms_text', models.TextField(help_text='Symptoms the patient described.')),
                ('urgency', models.CharField(choices=[('LOW', 'Low — mild discomfort'), ('MODERATE', 'Moderate — noticeable symptoms'), ('HIGH', 'High — significant pain or distress')], default='MODERATE', max_length=10)),
                ('drugs', models.JSONField(default=list, help_text='List of recommended OTC drugs with dosage info.')),
                ('warnings', models.JSONField(default=list, help_text="Warnings based on patient's medical history (allergies, interactions).")),
                ('disclaimer', models.TextField(default='⚠️ IMPORTANT: These recommendations are for TEMPORARY symptom relief only. They are NOT a substitute for professional medical diagnosis or treatment. You MUST visit a hospital or consult a healthcare professional as soon as possible. Do NOT rely solely on these suggestions. If symptoms worsen, seek emergency care immediately.')),
                ('medical_context_used', models.BooleanField(default=False, help_text='Whether patient medical records were considered.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('triage_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='triage.triagesession')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
