# Generated by Django 5.1.15 on 2026-02-21 17:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(choices=[('HIPAA', 'HIPAA'), ('GDPR', 'GDPR'), ('TRIAL', 'Clinical Trial'), ('DATA_SHARING', 'Data Sharing'), ('TOS', 'Terms of Service')], db_index=True, max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('electronic_signature', models.TextField(blank=True, default='')),
                ('version', models.CharField(default='1.0', max_length=20)),
            ],
            options={
                'db_table': 'consent_records',
                'ordering': ['-granted_at'],
            },
        ),
    ]
