# Generated by Django 5.1.15 on 2026-02-21 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consentrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['user', 'consent_type'], name='consent_rec_user_id_5843c5_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['expires_at'], name='consent_rec_expires_1c0fe4_idx'),
        ),
    ]
